; Generated by tools/generate_species_pool.py -- do not edit by hand.
; Sizes of the randomizer species pool in data/randomizer/species_pool.asm.
; Separate from the data so wram.asm can size its buffers.

DEF RANDO_POOL_SIZE EQU 146
DEF RANDO_ITEM_POOL_SIZE EQU 24
DEF RANDO_NUM_STARTER_SETS EQU 151
