; Generated by tools/generate_species_pool.py -- do not edit by hand.
; Valid randomizer species sorted by base-stat total, split into buckets so
; the runtime shuffle keeps replacements power-matched.

; Offsets into RandoPool, one per bucket plus an end sentinel.
RandoBucketBounds::
	table_width 1
	db 0
	db 19
	db 38
	db 57
	db 76
	db 95
	db 114
	db 133
	db 151
	assert_table_length RANDO_NUM_BUCKETS + 1

RandoPool::
	table_width 1
; bucket 0: BST 175-250
	db CATERPIE ; 175
	db WEEDLE ; 175
	db KAKUNA ; 180
	db METAPOD ; 180
	db MAGIKARP ; 185
	db ZUBAT ; 215
	db PIDGEY ; 216
	db RATTATA ; 218
	db JIGGLYPUFF ; 225
	db DIGLETT ; 230
	db SPEAROW ; 231
	db NIDORAN_M ; 233
	db EKANS ; 234
	db NIDORAN_F ; 235
	db PARAS ; 240
	db CHARMANDER ; 249
	db VULPIX ; 249
	db DRATINI ; 250
	db MEOWTH ; 250
; bucket 1: BST 250-275
	db SQUIRTLE ; 250
	db VENONAT ; 250
	db BULBASAUR ; 253
	db ABRA ; 255
	db ODDISH ; 255
	db PSYDUCK ; 255
	db CLEFAIRY ; 258
	db MANKEY ; 260
	db PIKACHU ; 260
	db POLIWAG ; 260
	db BELLSPROUT ; 270
	db CUBONE ; 270
	db GEODUDE ; 270
	db HORSEA ; 270
	db MACHOP ; 270
	db MAGNEMITE ; 270
	db DODUO ; 275
	db GASTLY ; 275
	db GRIMER ; 275
; bucket 2: BST 275-310
	db SLOWPOKE ; 275
	db VOLTORB ; 275
	db EEVEE ; 280
	db EXEGGCUTE ; 280
	db GROWLITHE ; 280
	db SANDSHREW ; 280
	db SEEL ; 280
	db SHELLDER ; 280
	db DITTO ; 282
	db DROWZEE ; 285
	db GOLDEEN ; 285
	db STARYU ; 285
	db TENTACOOL ; 285
	db KOFFING ; 295
	db PIDGEOTTO ; 299
	db KABUTO ; 300
	db KRABBY ; 300
	db OMANYTE ; 300
	db NIDORINA ; 310
; bucket 3: BST 310-385
	db NIDORINO ; 310
	db RHYHORN ; 315
	db GLOOM ; 320
	db CHARMELEON ; 325
	db IVYSAUR ; 325
	db WARTORTLE ; 325
	db KADABRA ; 330
	db POLIWHIRL ; 335
	db GRAVELER ; 345
	db MACHOKE ; 345
	db PONYTA ; 345
	db WEEPINBELL ; 345
	db DRAGONAIR ; 350
	db HAUNTER ; 350
	db BUTTERFREE ; 357
	db RATICATE ; 373
	db MR_MIME ; 380
	db BEEDRILL ; 382
	db DUGTRIO ; 385
; bucket 4: BST 389-415
	db FARFETCHD ; 389
	db JYNX ; 395
	db PRIMEAPE ; 400
	db SLOWBRO ; 400
	db WIGGLYTUFF ; 400
	db CLEFABLE ; 403
	db ALAKAZAM ; 405
	db LICKITUNG ; 405
	db PERSIAN ; 405
	db VENOMOTH ; 405
	db HITMONCHAN ; 410
	db HITMONLEE ; 410
	db MAGNETON ; 410
	db NIDOKING ; 410
	db NIDOQUEEN ; 410
	db FEAROW ; 411
	db ARBOK ; 415
	db CHANSEY ; 415
	db ELECTABUZZ ; 415
; bucket 5: BST 415-424
	db MAGMAR ; 415
	db ONIX ; 415
	db PORYGON ; 415
	db PIDGEOT ; 416
	db SANDSLASH ; 416
	db DODRIO ; 420
	db GOLDUCK ; 420
	db HYPNO ; 420
	db KANGASKHAN ; 420
	db MAROWAK ; 420
	db POLIWRATH ; 420
	db RAICHU ; 420
	db SCYTHER ; 420
	db SEADRA ; 420
	db SEAKING ; 420
	db TANGELA ; 420
	db VICTREEBEL ; 420
	db GOLBAT ; 421
	db NINETALES ; 424
; bucket 6: BST 425-435
	db BLASTOISE ; 425
	db CHARIZARD ; 425
	db DEWGONG ; 425
	db ELECTRODE ; 425
	db GENGAR ; 425
	db PARASECT ; 425
	db VENUSAUR ; 425
	db FLAREON ; 430
	db GOLEM ; 430
	db JOLTEON ; 430
	db KABUTOPS ; 430
	db MUK ; 430
	db OMASTAR ; 430
	db PINSIR ; 430
	db RAPIDASH ; 430
	db SNORLAX ; 430
	db VAPOREON ; 430
	db STARMIE ; 435
	db TENTACRUEL ; 435
; bucket 7: BST 435-590
	db VILEPLUME ; 435
	db AERODACTYL ; 440
	db RHYDON ; 440
	db WEEZING ; 440
	db KINGLER ; 445
	db LAPRAS ; 450
	db MACHAMP ; 450
	db TAUROS ; 450
	db ARCANINE ; 455
	db EXEGGUTOR ; 455
	db CLOYSTER ; 480
	db GYARADOS ; 480
	db ARTICUNO ; 485
	db ZAPDOS ; 490
	db MOLTRES ; 495
	db DRAGONITE ; 500
	db MEW ; 500
	db MEWTWO ; 590
	assert_table_length RANDO_POOL_SIZE

; bit 0 = CUT, bit 1 = SURF, bit 2 = STRENGTH
; indexed by internal species index
RandoHmLearners::
	table_width 1
	db 0
	db 7
	db 7
	db 1
	db 5
	db 1
	db 0
	db 7
	db 7
	db 1
	db 4
	db 7
	db 0
	db 6
	db 5
	db 1
	db 7
	db 5
	db 5
	db 6
	db 5
	db 7
	db 6
	db 2
	db 2
	db 0
	db 5
	db 3
	db 0
	db 7
	db 1
	db 0
	db 0
	db 5
	db 5
	db 5
	db 1
	db 7
	db 0
	db 5
	db 4
	db 5
	db 7
	db 5
	db 5
	db 5
	db 5
	db 7
	db 5
	db 5
	db 0
	db 5
	db 0
	db 5
	db 0
	db 0
	db 0
	db 5
	db 6
	db 5
	db 7
	db 0
	db 0
	db 0
	db 7
	db 1
	db 7
	db 0
	db 0
	db 0
	db 5
	db 2
	db 2
	db 1
	db 1
	db 1
	db 0
	db 5
	db 7
	db 0
	db 0
	db 0
	db 1
	db 1
	db 3
	db 7
	db 0
	db 0
	db 3
	db 3
	db 3
	db 7
	db 2
	db 2
	db 0
	db 0
	db 5
	db 5
	db 3
	db 3
	db 5
	db 5
	db 1
	db 5
	db 5
	db 7
	db 5
	db 1
	db 5
	db 1
	db 6
	db 6
	db 1
	db 1
	db 1
	db 0
	db 5
	db 5
	db 5
	db 1
	db 0
	db 0
	db 0
	db 1
	db 1
	db 1
	db 5
	db 0
	db 7
	db 5
	db 1
	db 5
	db 7
	db 0
	db 0
	db 0
	db 6
	db 0
	db 7
	db 2
	db 0
	db 0
	db 5
	db 0
	db 5
	db 5
	db 0
	db 1
	db 0
	db 0
	db 1
	db 5
	db 3
	db 1
	db 5
	db 2
	db 0
	db 2
	db 2
	db 0
	db 0
	db 0
	db 0
	db 4
	db 4
	db 1
	db 5
	db 5
	db 5
	db 5
	db 0
	db 5
	db 0
	db 0
	db 0
	db 0
	db 5
	db 0
	db 5
	db 0
	db 5
	db 0
	db 0
	db 0
	db 0
	db 1
	db 1
	db 1
	db 1
	db 1
	db 1
	assert_table_length 191

; pool positions of species catchable before Surf is needed. If none of
; their replacements can learn a field move, the guardrail swaps one in.
DEF RANDO_NUM_ANCHORS EQU 88
RandoAnchors::
	table_width 1
	db 0
	db 1
	db 2
	db 3
	db 4
	db 5
	db 6
	db 7
	db 8
	db 9
	db 10
	db 11
	db 12
	db 13
	db 14
	db 15
	db 16
	db 18
	db 19
	db 20
	db 21
	db 22
	db 23
	db 24
	db 25
	db 26
	db 27
	db 28
	db 29
	db 30
	db 31
	db 32
	db 33
	db 34
	db 35
	db 37
	db 38
	db 39
	db 40
	db 41
	db 42
	db 43
	db 47
	db 48
	db 49
	db 50
	db 51
	db 52
	db 54
	db 58
	db 61
	db 63
	db 64
	db 65
	db 67
	db 71
	db 72
	db 73
	db 74
	db 75
	db 76
	db 79
	db 80
	db 83
	db 84
	db 86
	db 87
	db 91
	db 92
	db 93
	db 95
	db 96
	db 99
	db 100
	db 101
	db 102
	db 103
	db 107
	db 109
	db 110
	db 125
	db 127
	db 132
	db 136
	db 137
	db 140
	db 142
	db 144
	assert_table_length RANDO_NUM_ANCHORS
