; Generated by tools/generate_species_pool.py -- do not edit by hand.
; Valid randomizer species sorted by base-stat total, with the range of
; positions each may be exchanged with.

RandoPool::
	table_width 1
	db CATERPIE ; 175
	db WEEDLE ; 175
	db KAKUNA ; 180
	db METAPOD ; 180
	db MAGIKARP ; 185
	db ZUBAT ; 215
	db PIDGEY ; 216
	db RATTATA ; 218
	db JIGGLYPUFF ; 225
	db DIGLETT ; 230
	db SPEAROW ; 231
	db NIDORAN_M ; 233
	db EKANS ; 234
	db NIDORAN_F ; 235
	db PARAS ; 240
	db CHARMANDER ; 249
	db VULPIX ; 249
	db DRATINI ; 250
	db MEOWTH ; 250
	db SQUIRTLE ; 250
	db VENONAT ; 250
	db BULBASAUR ; 253
	db ABRA ; 255
	db ODDISH ; 255
	db PSYDUCK ; 255
	db CLEFAIRY ; 258
	db MANKEY ; 260
	db PIKACHU ; 260
	db POLIWAG ; 260
	db BELLSPROUT ; 270
	db CUBONE ; 270
	db GEODUDE ; 270
	db HORSEA ; 270
	db MACHOP ; 270
	db MAGNEMITE ; 270
	db DODUO ; 275
	db GASTLY ; 275
	db GRIMER ; 275
	db SLOWPOKE ; 275
	db VOLTORB ; 275
	db EEVEE ; 280
	db EXEGGCUTE ; 280
	db GROWLITHE ; 280
	db SANDSHREW ; 280
	db SEEL ; 280
	db SHELLDER ; 280
	db DITTO ; 282
	db DROWZEE ; 285
	db GOLDEEN ; 285
	db STARYU ; 285
	db TENTACOOL ; 285
	db KOFFING ; 295
	db PIDGEOTTO ; 299
	db KABUTO ; 300
	db KRABBY ; 300
	db OMANYTE ; 300
	db NIDORINA ; 310
	db NIDORINO ; 310
	db RHYHORN ; 315
	db GLOOM ; 320
	db CHARMELEON ; 325
	db IVYSAUR ; 325
	db WARTORTLE ; 325
	db KADABRA ; 330
	db POLIWHIRL ; 335
	db GRAVELER ; 345
	db MACHOKE ; 345
	db PONYTA ; 345
	db WEEPINBELL ; 345
	db DRAGONAIR ; 350
	db HAUNTER ; 350
	db BUTTERFREE ; 357
	db RATICATE ; 373
	db MR_MIME ; 380
	db BEEDRILL ; 382
	db DUGTRIO ; 385
	db FARFETCHD ; 389
	db JYNX ; 395
	db PRIMEAPE ; 400
	db SLOWBRO ; 400
	db WIGGLYTUFF ; 400
	db CLEFABLE ; 403
	db ALAKAZAM ; 405
	db LICKITUNG ; 405
	db PERSIAN ; 405
	db VENOMOTH ; 405
	db HITMONCHAN ; 410
	db HITMONLEE ; 410
	db MAGNETON ; 410
	db NIDOKING ; 410
	db NIDOQUEEN ; 410
	db FEAROW ; 411
	db ARBOK ; 415
	db CHANSEY ; 415
	db ELECTABUZZ ; 415
	db MAGMAR ; 415
	db ONIX ; 415
	db PORYGON ; 415
	db PIDGEOT ; 416
	db SANDSLASH ; 416
	db DODRIO ; 420
	db GOLDUCK ; 420
	db HYPNO ; 420
	db KANGASKHAN ; 420
	db MAROWAK ; 420
	db POLIWRATH ; 420
	db RAICHU ; 420
	db SCYTHER ; 420
	db SEADRA ; 420
	db SEAKING ; 420
	db TANGELA ; 420
	db VICTREEBEL ; 420
	db GOLBAT ; 421
	db NINETALES ; 424
	db BLASTOISE ; 425
	db CHARIZARD ; 425
	db DEWGONG ; 425
	db ELECTRODE ; 425
	db GENGAR ; 425
	db PARASECT ; 425
	db VENUSAUR ; 425
	db FLAREON ; 430
	db GOLEM ; 430
	db JOLTEON ; 430
	db KABUTOPS ; 430
	db MUK ; 430
	db OMASTAR ; 430
	db PINSIR ; 430
	db RAPIDASH ; 430
	db SNORLAX ; 430
	db VAPOREON ; 430
	db STARMIE ; 435
	db TENTACRUEL ; 435
	db VILEPLUME ; 435
	db AERODACTYL ; 440
	db RHYDON ; 440
	db WEEZING ; 440
	db KINGLER ; 445
	db LAPRAS ; 450
	db MACHAMP ; 450
	db TAUROS ; 450
	db ARCANINE ; 455
	db EXEGGUTOR ; 455
	db CLOYSTER ; 480
	db GYARADOS ; 480
	db DRAGONITE ; 500
	assert_table_length RANDO_POOL_SIZE

RandoWindowLo::
	table_width 1
	db 0
	db 0
	db 0
	db 0
	db 0
	db 5
	db 5
	db 5
	db 5
	db 5
	db 5
	db 5
	db 5
	db 5
	db 8
	db 9
	db 9
	db 9
	db 9
	db 9
	db 9
	db 9
	db 11
	db 11
	db 11
	db 13
	db 14
	db 14
	db 14
	db 15
	db 15
	db 15
	db 15
	db 15
	db 15
	db 17
	db 17
	db 17
	db 17
	db 17
	db 22
	db 22
	db 22
	db 22
	db 22
	db 22
	db 25
	db 26
	db 26
	db 26
	db 26
	db 29
	db 35
	db 35
	db 35
	db 35
	db 46
	db 46
	db 51
	db 51
	db 52
	db 52
	db 52
	db 53
	db 56
	db 58
	db 58
	db 58
	db 58
	db 59
	db 59
	db 60
	db 65
	db 69
	db 69
	db 69
	db 71
	db 72
	db 72
	db 72
	db 72
	db 72
	db 72
	db 72
	db 72
	db 72
	db 72
	db 72
	db 72
	db 72
	db 72
	db 73
	db 73
	db 73
	db 73
	db 73
	db 73
	db 73
	db 73
	db 73
	db 74
	db 74
	db 74
	db 74
	db 74
	db 74
	db 74
	db 74
	db 74
	db 74
	db 74
	db 74
	db 75
	db 76
	db 76
	db 76
	db 76
	db 76
	db 76
	db 76
	db 76
	db 77
	db 77
	db 77
	db 77
	db 77
	db 77
	db 77
	db 77
	db 77
	db 77
	db 78
	db 78
	db 78
	db 78
	db 78
	db 78
	db 82
	db 86
	db 86
	db 86
	db 92
	db 92
	db 134
	db 134
	db 141
	assert_table_length RANDO_POOL_SIZE

RandoWindowHi::
	table_width 1
	db 4
	db 4
	db 4
	db 4
	db 4
	db 13
	db 13
	db 13
	db 14
	db 21
	db 21
	db 24
	db 24
	db 25
	db 28
	db 34
	db 34
	db 39
	db 39
	db 39
	db 39
	db 39
	db 45
	db 45
	db 45
	db 46
	db 50
	db 50
	db 50
	db 51
	db 51
	db 51
	db 51
	db 51
	db 51
	db 55
	db 55
	db 55
	db 55
	db 55
	db 55
	db 55
	db 55
	db 55
	db 55
	db 55
	db 57
	db 57
	db 57
	db 57
	db 57
	db 59
	db 62
	db 63
	db 63
	db 63
	db 64
	db 64
	db 68
	db 70
	db 71
	db 71
	db 71
	db 71
	db 71
	db 72
	db 72
	db 72
	db 72
	db 75
	db 75
	db 76
	db 90
	db 99
	db 111
	db 112
	db 120
	db 130
	db 136
	db 136
	db 136
	db 136
	db 137
	db 137
	db 137
	db 137
	db 140
	db 140
	db 140
	db 140
	db 140
	db 140
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 142
	db 144
	db 144
	db 144
	db 144
	db 144
	db 144
	db 144
	db 145
	db 145
	db 145
	db 145
	db 145
	assert_table_length RANDO_POOL_SIZE

; position in RandoPool for each species index, 255 if not in the pool
RandoPoolPos::
	table_width 1
	db 255
	db 135
	db 103
	db 11
	db 25
	db 10
	db 39
	db 89
	db 79
	db 61
	db 142
	db 83
	db 41
	db 37
	db 118
	db 13
	db 90
	db 30
	db 58
	db 138
	db 141
	db 255
	db 144
	db 45
	db 50
	db 36
	db 107
	db 49
	db 114
	db 127
	db 110
	db 255
	db 255
	db 42
	db 96
	db 91
	db 6
	db 38
	db 63
	db 65
	db 93
	db 66
	db 73
	db 87
	db 86
	db 92
	db 119
	db 24
	db 47
	db 122
	db 255
	db 95
	db 255
	db 94
	db 88
	db 51
	db 255
	db 26
	db 44
	db 9
	db 140
	db 255
	db 255
	db 255
	db 76
	db 20
	db 145
	db 255
	db 255
	db 255
	db 35
	db 28
	db 77
	db 255
	db 255
	db 255
	db 46
	db 18
	db 54
	db 255
	db 255
	db 255
	db 16
	db 113
	db 27
	db 106
	db 255
	db 255
	db 17
	db 69
	db 53
	db 124
	db 32
	db 108
	db 255
	db 255
	db 43
	db 99
	db 55
	db 126
	db 8
	db 80
	db 40
	db 121
	db 123
	db 130
	db 33
	db 5
	db 12
	db 14
	db 64
	db 105
	db 1
	db 2
	db 74
	db 255
	db 100
	db 78
	db 75
	db 85
	db 116
	db 255
	db 255
	db 0
	db 3
	db 71
	db 139
	db 255
	db 101
	db 102
	db 112
	db 255
	db 129
	db 4
	db 255
	db 255
	db 125
	db 255
	db 137
	db 143
	db 255
	db 117
	db 81
	db 136
	db 84
	db 104
	db 255
	db 70
	db 22
	db 82
	db 52
	db 98
	db 131
	db 21
	db 120
	db 132
	db 255
	db 48
	db 109
	db 255
	db 255
	db 255
	db 255
	db 67
	db 128
	db 7
	db 72
	db 57
	db 56
	db 31
	db 97
	db 134
	db 255
	db 34
	db 255
	db 255
	db 15
	db 19
	db 60
	db 62
	db 115
	db 255
	db 255
	db 255
	db 255
	db 23
	db 59
	db 133
	db 29
	db 68
	db 111
	assert_table_length 191

; bit 0 = CUT, bit 1 = SURF, bit 2 = STRENGTH
; indexed by internal species index
RandoHmLearners::
	table_width 1
	db 0
	db 7
	db 7
	db 1
	db 5
	db 1
	db 0
	db 7
	db 7
	db 1
	db 4
	db 7
	db 0
	db 6
	db 5
	db 1
	db 7
	db 5
	db 5
	db 6
	db 5
	db 7
	db 6
	db 2
	db 2
	db 0
	db 5
	db 3
	db 0
	db 7
	db 1
	db 0
	db 0
	db 5
	db 5
	db 5
	db 1
	db 7
	db 0
	db 5
	db 4
	db 5
	db 7
	db 5
	db 5
	db 5
	db 5
	db 7
	db 5
	db 5
	db 0
	db 5
	db 0
	db 5
	db 0
	db 0
	db 0
	db 5
	db 6
	db 5
	db 7
	db 0
	db 0
	db 0
	db 7
	db 1
	db 7
	db 0
	db 0
	db 0
	db 5
	db 2
	db 2
	db 1
	db 1
	db 1
	db 0
	db 5
	db 7
	db 0
	db 0
	db 0
	db 1
	db 1
	db 3
	db 7
	db 0
	db 0
	db 3
	db 3
	db 3
	db 7
	db 2
	db 2
	db 0
	db 0
	db 5
	db 5
	db 3
	db 3
	db 5
	db 5
	db 1
	db 5
	db 5
	db 7
	db 5
	db 1
	db 5
	db 1
	db 6
	db 6
	db 1
	db 1
	db 1
	db 0
	db 5
	db 5
	db 5
	db 1
	db 0
	db 0
	db 0
	db 1
	db 1
	db 1
	db 5
	db 0
	db 7
	db 5
	db 1
	db 5
	db 7
	db 0
	db 0
	db 0
	db 6
	db 0
	db 7
	db 2
	db 0
	db 0
	db 5
	db 0
	db 5
	db 5
	db 0
	db 1
	db 0
	db 0
	db 1
	db 5
	db 3
	db 1
	db 5
	db 2
	db 0
	db 2
	db 2
	db 0
	db 0
	db 0
	db 0
	db 4
	db 4
	db 1
	db 5
	db 5
	db 5
	db 5
	db 0
	db 5
	db 0
	db 0
	db 0
	db 0
	db 5
	db 0
	db 5
	db 0
	db 5
	db 0
	db 0
	db 0
	db 0
	db 1
	db 1
	db 1
	db 1
	db 1
	db 1
	assert_table_length 191

; pool positions of species catchable before Surf is needed. If none of
; their replacements can learn a field move, the guardrail swaps one in.
DEF RANDO_NUM_ANCHORS EQU 88
RandoAnchors::
	table_width 1
	db 0
	db 1
	db 2
	db 3
	db 4
	db 5
	db 6
	db 7
	db 8
	db 9
	db 10
	db 11
	db 12
	db 13
	db 14
	db 15
	db 16
	db 18
	db 19
	db 20
	db 21
	db 22
	db 23
	db 24
	db 25
	db 26
	db 27
	db 28
	db 29
	db 30
	db 31
	db 32
	db 33
	db 34
	db 35
	db 37
	db 38
	db 39
	db 40
	db 41
	db 42
	db 43
	db 47
	db 48
	db 49
	db 50
	db 51
	db 52
	db 54
	db 58
	db 61
	db 63
	db 64
	db 65
	db 67
	db 71
	db 72
	db 73
	db 74
	db 75
	db 76
	db 79
	db 80
	db 83
	db 84
	db 86
	db 87
	db 91
	db 92
	db 93
	db 95
	db 96
	db 99
	db 100
	db 101
	db 102
	db 103
	db 107
	db 109
	db 110
	db 125
	db 127
	db 132
	db 136
	db 137
	db 140
	db 142
	db 144
	assert_table_length RANDO_NUM_ANCHORS

; what each species evolves into, 0 for none, by internal species index
RandoEvolvesTo::
	table_width 1
	db 0
	db 0
	db 0
	db NIDORINO
	db CLEFABLE
	db FEAROW
	db ELECTRODE
	db 0
	db 0
	db VENUSAUR
	db 0
	db 0
	db EXEGGUTOR
	db MUK
	db 0
	db NIDORINA
	db 0
	db MAROWAK
	db RHYDON
	db 0
	db 0
	db 0
	db 0
	db CLOYSTER
	db TENTACRUEL
	db HAUNTER
	db 0
	db STARMIE
	db 0
	db 0
	db 0
	db 0
	db 0
	db ARCANINE
	db 0
	db 0
	db PIDGEOTTO
	db SLOWBRO
	db ALAKAZAM
	db GOLEM
	db 0
	db MACHAMP
	db 0
	db 0
	db 0
	db 0
	db 0
	db GOLDUCK
	db HYPNO
	db 0
	db 0
	db 0
	db 0
	db 0
	db 0
	db WEEZING
	db 0
	db PRIMEAPE
	db DEWGONG
	db DUGTRIO
	db 0
	db 0
	db 0
	db 0
	db 0
	db VENOMOTH
	db 0
	db 0
	db 0
	db 0
	db DODRIO
	db POLIWHIRL
	db 0
	db 0
	db 0
	db 0
	db 0
	db PERSIAN
	db KINGLER
	db 0
	db 0
	db 0
	db NINETALES
	db 0
	db RAICHU
	db 0
	db 0
	db 0
	db DRAGONAIR
	db DRAGONITE
	db KABUTOPS
	db 0
	db SEADRA
	db 0
	db 0
	db 0
	db SANDSLASH
	db 0
	db OMASTAR
	db 0
	db WIGGLYTUFF
	db 0
	db FLAREON
	db 0
	db 0
	db 0
	db MACHOKE
	db GOLBAT
	db ARBOK
	db PARASECT
	db POLIWRATH
	db 0
	db KAKUNA
	db BEEDRILL
	db 0
	db 0
	db 0
	db 0
	db 0
	db 0
	db 0
	db 0
	db 0
	db METAPOD
	db BUTTERFREE
	db 0
	db 0
	db 0
	db 0
	db 0
	db 0
	db 0
	db 0
	db GYARADOS
	db 0
	db 0
	db 0
	db 0
	db 0
	db 0
	db 0
	db 0
	db 0
	db 0
	db 0
	db 0
	db 0
	db GENGAR
	db KADABRA
	db 0
	db PIDGEOT
	db 0
	db 0
	db IVYSAUR
	db 0
	db 0
	db 0
	db SEAKING
	db 0
	db 0
	db 0
	db 0
	db 0
	db RAPIDASH
	db 0
	db RATICATE
	db 0
	db NIDOKING
	db NIDOQUEEN
	db GRAVELER
	db 0
	db 0
	db 0
	db MAGNETON
	db 0
	db 0
	db CHARMELEON
	db WARTORTLE
	db CHARIZARD
	db BLASTOISE
	db 0
	db 0
	db 0
	db 0
	db 0
	db GLOOM
	db VILEPLUME
	db 0
	db WEEPINBELL
	db VICTREEBEL
	db 0
	assert_table_length 191

; Starter sets. The player takes one and the rival the next along, so the
; order carries the matchup. All but the first few are type cycles: each
; beats the next and loses to the one before.
RandoStarterTriples::
	table_width 3
	db FLAREON, VAPOREON, JOLTEON ; Eeveelutions
	db MOLTRES, ARTICUNO, ZAPDOS ; Legendary birds
	db CHARMANDER, SQUIRTLE, BULBASAUR ; Vanilla
	db EKANS, KOFFING, MEOWTH ; Team Rocket
	db OMANYTE, KABUTO, AERODACTYL ; Fossils
	db LAPRAS, SNORLAX, AERODACTYL ; Titans
	db MAGIKARP, CATERPIE, WEEDLE ; Hard mode
	db ABRA, BELLSPROUT, PARAS ; cycle
	db CUBONE, ELECTABUZZ, GOLDEEN ; cycle
	db DIGLETT, GASTLY, EXEGGCUTE ; cycle
	db DODUO, GEODUDE, JYNX ; cycle
	db DROWZEE, GRIMER, PINSIR ; cycle
	db FARFETCHD, HITMONCHAN, ONIX ; cycle
	db GROWLITHE, ODDISH, HORSEA ; cycle
	db HITMONLEE, PONYTA, SCYTHER ; cycle
	db KRABBY, MAGMAR, TANGELA ; cycle
	db MACHOP, RHYHORN, PIDGEY ; cycle
	db MAGNEMITE, POLIWAG, SANDSHREW ; cycle
	db SLOWPOKE, TENTACOOL, VOLTORB ; cycle
	db ABRA, ZUBAT, VENONAT ; cycle
	db BELLSPROUT, PSYDUCK, VULPIX ; cycle
	db CUBONE, PIKACHU, SEEL ; cycle
	db GEODUDE, SPEAROW, MANKEY ; cycle
	db BULBASAUR, SHELLDER, DODUO ; cycle
	db CATERPIE, DROWZEE, NIDORAN_F ; cycle
	db CHARMANDER, EXEGGCUTE, STARYU ; cycle
	db DIGLETT, NIDORAN_M, PARAS ; cycle
	db GASTLY, MR_MIME, JYNX ; cycle
	db EKANS, PINSIR, ONIX ; cycle
	db ELECTABUZZ, HORSEA, RHYHORN ; cycle
	db FARFETCHD, HITMONLEE, LAPRAS ; cycle
	db FLAREON, ODDISH, GOLDEEN ; cycle
	db GRIMER, SCYTHER, SLOWPOKE ; cycle
	db GROWLITHE, TANGELA, MAGIKARP ; cycle
	db HITMONCHAN, OMANYTE, PIDGEY ; cycle
	db JOLTEON, KRABBY, SANDSHREW ; cycle
	db KABUTO, VENONAT, TENTACOOL ; cycle
	db AERODACTYL, VOLTORB, POLIWAG ; cycle
	db BELLSPROUT, SEEL, MAGMAR ; cycle
	db BULBASAUR, PSYDUCK, PONYTA ; cycle
	db CUBONE, MAGNEMITE, SHELLDER ; cycle
	db DIGLETT, PIKACHU, SQUIRTLE ; cycle
	db DROWZEE, ZUBAT, WEEDLE ; cycle
	db EXEGGCUTE, VAPOREON, VULPIX ; cycle
	db LAPRAS, SPEAROW, MACHOP ; cycle
	db ABRA, KOFFING, CATERPIE ; cycle
	db DODUO, ELECTABUZZ, STARYU ; cycle
	db FARFETCHD, MANKEY, OMANYTE ; cycle
	db GEODUDE, NIDORAN_F, PARAS ; cycle
	db JYNX, NIDORAN_M, PINSIR ; cycle
	db CHARMANDER, ODDISH, KRABBY ; cycle
	db EKANS, SCYTHER, VENONAT ; cycle
	db FLAREON, TANGELA, HORSEA ; cycle
	db GASTLY, SLOWPOKE, ONIX ; cycle
	db GOLDEEN, KABUTO, VOLTORB ; cycle
	db GROWLITHE, WEEDLE, TENTACOOL ; cycle
	db HITMONCHAN, RHYHORN, SPEAROW ; cycle
	db MAGIKARP, SANDSHREW, PIKACHU ; cycle
	db BELLSPROUT, POLIWAG, PONYTA ; cycle
	db BULBASAUR, SEEL, VULPIX ; cycle
	db CUBONE, JOLTEON, PSYDUCK ; cycle
	db DIGLETT, MAGNEMITE, STARYU ; cycle
	db EXEGGCUTE, SHELLDER, MAGMAR ; cycle
	db GEODUDE, PIDGEY, HITMONLEE ; cycle
	db LAPRAS, ZUBAT, MANKEY ; cycle
	db ABRA, NIDORAN_F, PINSIR ; cycle
	db AERODACTYL, MACHOP, GOLDEEN ; cycle
	db CATERPIE, JYNX, GRIMER ; cycle
	db CHARMANDER, PARAS, VAPOREON ; cycle
	db DODUO, JOLTEON, SQUIRTLE ; cycle
	db DROWZEE, KOFFING, SCYTHER ; cycle
	db NIDORAN_M, TANGELA, ONIX ; cycle
	db ELECTABUZZ, OMANYTE, SANDSHREW ; cycle
	db FARFETCHD, ODDISH, RHYHORN ; cycle
	db FLAREON, VENONAT, SLOWPOKE ; cycle
	db BELLSPROUT, HORSEA, KABUTO ; cycle
	db BULBASAUR, KRABBY, GROWLITHE ; cycle
	db CATERPIE, TENTACOOL, MAGMAR ; cycle
	db CUBONE, VOLTORB, MAGIKARP ; cycle
	db DODUO, MAGNEMITE, PSYDUCK ; cycle
	db EKANS, EXEGGCUTE, WEEDLE ; cycle
	db GEODUDE, PIKACHU, POLIWAG ; cycle
	db HITMONCHAN, PONYTA, JYNX ; cycle
	db HITMONLEE, OMANYTE, SPEAROW ; cycle
	db MACHOP, ONIX, ZUBAT ; cycle
	db ODDISH, SHELLDER, VULPIX ; cycle
	db ABRA, GASTLY, SCYTHER ; cycle
	db AERODACTYL, MANKEY, RHYHORN ; cycle
	db CHARMANDER, TANGELA, SEEL ; cycle
	db DIGLETT, ELECTABUZZ, VAPOREON ; cycle
	db FLAREON, PARAS, SQUIRTLE ; cycle
	db KOFFING, PINSIR, SANDSHREW ; cycle
	db BELLSPROUT, LAPRAS, PIDGEY ; cycle
	db BULBASAUR, STARYU, KABUTO ; cycle
	db CATERPIE, SLOWPOKE, NIDORAN_M ; cycle
	db EXEGGCUTE, VENONAT, GRIMER ; cycle
	db NIDORAN_F, SCYTHER, WEEDLE ; cycle
	db DIGLETT, JOLTEON, GOLDEEN ; cycle
	db DODUO, PIKACHU, HORSEA ; cycle
	db DROWZEE, EKANS, PARAS ; cycle
	db FARFETCHD, MACHOP, GEODUDE ; cycle
	db HITMONLEE, RHYHORN, ZUBAT ; cycle
	db JYNX, TENTACOOL, VULPIX ; cycle
	db KRABBY, ONIX, MAGNEMITE ; cycle
	db MAGIKARP, MAGMAR, ODDISH ; cycle
	db PONYTA, TANGELA, SHELLDER ; cycle
	db PSYDUCK, SANDSHREW, VOLTORB ; cycle
	db BELLSPROUT, SQUIRTLE, GROWLITHE ; cycle
	db MANKEY, ONIX, PIDGEY ; cycle
	db AERODACTYL, BULBASAUR, VAPOREON ; cycle
	db CHARMANDER, PINSIR, GOLDEEN ; cycle
	db CUBONE, GASTLY, PARAS ; cycle
	db DIGLETT, VOLTORB, SEEL ; cycle
	db DODUO, HITMONCHAN, LAPRAS ; cycle
	db ELECTABUZZ, SPEAROW, EXEGGCUTE ; cycle
	db GEODUDE, JOLTEON, STARYU ; cycle
	db KABUTO, ODDISH, POLIWAG ; cycle
	db KOFFING, TANGELA, SLOWPOKE ; cycle
	db FARFETCHD, VENONAT, JYNX ; cycle
	db FLAREON, PINSIR, OMANYTE ; cycle
	db GRIMER, PARAS, WEEDLE ; cycle
	db KRABBY, RHYHORN, PIKACHU ; cycle
	db AERODACTYL, SCYTHER, TENTACOOL ; cycle
	db BULBASAUR, HORSEA, MAGMAR ; cycle
	db CUBONE, NIDORAN_F, EXEGGCUTE ; cycle
	db GEODUDE, MAGNEMITE, MAGIKARP ; cycle
	db ODDISH, SEEL, PONYTA ; cycle
	db POLIWAG, VULPIX, TANGELA ; cycle
	db BELLSPROUT, OMANYTE, ZUBAT ; cycle
	db CHARMANDER, WEEDLE, SLOWPOKE ; cycle
	db DODUO, HITMONLEE, GOLDEEN ; cycle
	db ELECTABUZZ, PSYDUCK, ONIX ; cycle
	db EXEGGCUTE, SANDSHREW, NIDORAN_M ; cycle
	db GROWLITHE, PARAS, SHELLDER ; cycle
	db MAGNEMITE, SQUIRTLE, RHYHORN ; cycle
	db BELLSPROUT, STARYU, FLAREON ; cycle
	db DODUO, VOLTORB, VAPOREON ; cycle
	db GEODUDE, ZUBAT, HITMONCHAN ; cycle
	db GROWLITHE, PINSIR, LAPRAS ; cycle
	db JYNX, MACHOP, OMANYTE ; cycle
	db BULBASAUR, CATERPIE, VENONAT ; cycle
	db CUBONE, EKANS, TANGELA ; cycle
	db EXEGGCUTE, MANKEY, PONYTA ; cycle
	db HORSEA, ONIX, JOLTEON ; cycle
	db JYNX, PIDGEY, SCYTHER ; cycle
	db AERODACTYL, ODDISH, PSYDUCK ; cycle
	db DIGLETT, GRIMER, TANGELA ; cycle
	db GASTLY, PINSIR, RHYHORN ; cycle
	db JYNX, SPEAROW, WEEDLE ; cycle
	db KABUTO, PARAS, KRABBY ; cycle
	db ONIX, PIKACHU, SHELLDER ; cycle
	assert_table_length RANDO_NUM_STARTER_SETS
